# Generated by Django 2.0.4 on 2018-06-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
                'ordering': ('user__username',),
            },
        ),
    ]
