# Generated by Django 2.0.4 on 2018-06-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
        migrations.AddField(
            model_name='location',
            name='devices',
            field=models.ManyToManyField(blank=True, null=True, to='locations.Device'),
        ),
    ]
