# Generated by Django 2.0.4 on 2018-07-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20180628_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='devices',
            field=models.ManyToManyField(blank=True, to='locations.Device'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='locations',
            field=models.ManyToManyField(blank=True, to='locations.Location'),
        ),
    ]
