# Generated by Django 2.0.4 on 2018-12-27 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_location_new_proxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name']},
        ),
    ]
