# Generated by Django 2.0.4 on 2018-12-27 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20181227_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='new_proxy',
        ),
    ]
