# Generated by Django 2.0.4 on 2018-12-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_remove_location_new_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='new_proxy',
            field=models.BooleanField(default=False),
        ),
    ]
