# Generated by Django 2.0.4 on 2018-12-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_location_new_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
