# Generated by Django 2.0.4 on 2018-12-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20181227_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='new_proxy',
            field=models.BooleanField(default=False),
        ),
    ]
