# Generated by Django 2.0.4 on 2018-12-27 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0015_location_new_proxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='new_proxy',
        ),
    ]
