# Generated by Django 2.0.4 on 2019-03-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0020_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('read', 'READ'), ('ov', 'OV'), ('modes', 'MODES')], default='read', max_length=100),
        ),
    ]
