# Generated by Django 2.0.4 on 2019-03-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0021_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, default='client__name', max_length=100, null=True),
        ),
    ]
