# Generated by Django 2.0.4 on 2019-03-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0022_auto_20190325_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.BooleanField(default=False, help_text='Admins have access to all Locations. Only for K&L staff.'),
        ),
    ]
