# Generated by Django 2.0.4 on 2019-04-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0024_auto_20190325_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_mobile_login',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='new_email_update',
            field=models.DateField(default=None),
        ),
    ]
