# Generated by Django 2.0.4 on 2019-04-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0026_auto_20190404_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_mobile_login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='new_email_update',
        ),
    ]
