# Generated by Django 2.0.4 on 2019-04-04 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0027_auto_20190404_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_mobile_login',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='new_email_update',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
