# Generated by Django 2.0.4 on 2019-04-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0028_auto_20190404_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_mobile_login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='new_email_update',
        ),
    ]
