# Generated by Django 2.0.4 on 2019-04-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0029_auto_20190404_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_mobile_login',
            field=models.DateField(null=True),
        ),
    ]
