# Generated by Django 2.0.4 on 2019-04-04 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0030_userprofile_last_mobile_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_mobile_login',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
