# Generated by Django 2.0.4 on 2019-04-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0031_auto_20190404_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_mobile_login',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
