# Generated by Django 2.0.4 on 2019-04-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0032_auto_20190404_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='test',
        ),
    ]
