# Generated by Django 2.0.4 on 2019-04-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0033_remove_userprofile_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
