# Generated by Django 2.0.4 on 2019-04-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0034_userprofile_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_mobile_login',
            field=models.DateField(blank=True, null=True),
        ),
    ]
