# Generated by Django 2.0.4 on 2019-04-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0036_auto_20190404_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='new_email_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
