# Generated by Django 2.0.4 on 2019-04-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0037_userprofile_new_email_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='test',
        ),
    ]
