# Generated by Django 2.0.4 on 2019-04-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0038_remove_userprofile_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_portal_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
