# Generated by Django 2.0.4 on 2019-04-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0039_userprofile_last_portal_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='admin_emails',
            field=models.TextField(blank=True, help_text='Comma delimited list of admin email addresses.'),
        ),
    ]
