# Generated by Django 2.0.4 on 2019-04-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0040_location_admin_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='has_notifications',
            field=models.BooleanField(default=True, help_text='Does this installation send notifications for alarms?'),
        ),
        migrations.AddField(
            model_name='location',
            name='notify_admins',
            field=models.BooleanField(default=True, help_text='Also notify admin emails for alarms?'),
        ),
    ]
