# Generated by Django 2.0.4 on 2020-03-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0041_auto_20190415_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name_field', models.CharField(db_column='\ufeff"Name"', max_length=16)),
                ('name_title', models.IntegerField(blank=True, db_column='Name: Title', null=True)),
                ('name_first', models.CharField(db_column='Name: First', max_length=11)),
                ('name_middle', models.IntegerField(blank=True, db_column='Name: Middle', null=True)),
                ('name_last', models.CharField(db_column='Name: Last', max_length=11)),
                ('email', models.CharField(db_column='Email', max_length=29)),
                ('password', models.CharField(db_column='Password', max_length=9)),
                ('user_status', models.CharField(db_column='User Status', max_length=8)),
                ('user_roles', models.CharField(blank=True, db_column='User Roles', max_length=119, null=True)),
                ('people', models.CharField(blank=True, db_column='People', max_length=16, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=19, null=True)),
                ('tab_company', models.CharField(blank=True, db_column='TAB Company', max_length=27, null=True)),
                ('support', models.IntegerField(blank=True, db_column='Support', null=True)),
                ('open_sr_assigned', models.DecimalField(db_column='Open SR Assigned', decimal_places=0, max_digits=38)),
                ('sr_created', models.DecimalField(db_column='SR Created', decimal_places=0, max_digits=38)),
                ('created', models.DateTimeField(blank=True, db_column='Created', null=True)),
                ('client_portal_company', models.CharField(blank=True, db_column='Client Portal Company', max_length=25, null=True)),
                ('given_password', models.CharField(blank=True, db_column='Given Password', max_length=10, null=True)),
                ('payroll', models.IntegerField(blank=True, db_column='Payroll', null=True)),
                ('jacktestcompany', models.CharField(blank=True, db_column='JackTestCompany', max_length=21, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='historicalkwinfo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='client',
        ),
        migrations.RemoveField(
            model_name='location',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='client',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Dealer',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='HistoricalKWInfo',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
