# Generated by Django 2.0.4 on 2020-03-31 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0043_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
