# Generated by Django 2.0.4 on 2020-04-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0045_product_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurement',
            field=models.CharField(choices=[('Tied Bunch', 'Tied Bunch'), ('Kg', 'Kg'), ('Unit', 'Unit')], default='kg', max_length=100),
        ),
    ]
